baseURL: https://eunice-portfolio.netlify.app/
languageCode: en-us
title: Eunice Liu
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Welcome to my website
    subtitle: |-
      London Business School MFA
    title: Hi, my name is Eunice Liu
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom NW1 4SA
        street: Regent's Park 
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: eliu.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (44) 7409569257
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Eunice Liu
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: fa-twitter
      #  label: Twitter
      #  url: https://www.twitter.com #change to my own account
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/euniceliu912/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/eunice_liu_/
      - icon: fa-github
        label: GitHub
        url: https://github.com/Liu-Yucen-Eunice
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/euniceliuyc/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: My CV
        url: https://drive.google.com/file/d/1YDirCy3PA_b47Q7Fh2MsLzUQQZWb3UnM/view?usp=sharing
   # button2:
    #  - name: Log In
     #   url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs/self_intro
     # - name: Generic Blog
      #  url: blogs/ipsum
     # - name: Elements
     #   url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: me.jpg
        subtitle: Self Introduction
        title: Eunice Liu's Biography
        url: blogs/self_intro
      - image: ust.jpg
        subtitle: My Experience
        title: Studies and Internships
        url: blogs/exp
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
