---
title: "Youth Risk Behavior Surveillance"
date: '2021-10-20'
description: Youth Risk Behavior Surveillance
draft: no
image: view4.jpg
keywords: ''
slug: youth
categories:
- ''
- ''
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<div id="youth-risk-behavior-surveillance" class="section level1">
<h1>Youth Risk Behavior Surveillance</h1>
<p>Every two years, the Centers for Disease Control and Prevention conduct the <a href="https://www.cdc.gov/healthyyouth/data/yrbs/index.htm">Youth Risk Behavior Surveillance System (YRBSS)</a> survey, where it takes data from high schoolers (9th through 12th grade), to analyze health patterns. You will work with a selected group of variables from a random sample of observations during one of the years the YRBSS was conducted.</p>
<div id="load-the-data" class="section level2">
<h2>Load the data</h2>
<p>This data is part of the <code>openintro</code> textbook and we can load and inspect it. There are observations on 13 different variables, some categorical and some numerical. The meaning of each variable can be found by bringing up the help file:</p>
<p>?yrbss</p>
<pre class="r"><code>data(yrbss)
glimpse(yrbss)</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15, 1…
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;fema…
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, …
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;not&quot;…
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Africa…
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88, 1…
## $ weight                   &lt;dbl&gt; NA, NA, 84.4, 55.8, 46.7, 67.1, 131.5, 71.2, …
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did not …
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did not…
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, 7, …
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;,…
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, 7, …
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;&lt;5&quot;…</code></pre>
<p>Before you carry on with your analysis, it’s is always a good idea to check with <code>skimr::skim()</code> to get a feel for missing values, summary statistics of numerical variables, and a very rough histogram.</p>
<pre class="r"><code># Inspecting Data set
yrbss %&gt;% 
  skimr::skim()</code></pre>
<table>
<caption><span id="tab:unnamed-chunk-2">Table 1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">Piped data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">13583</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">12</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">grade</td>
<td align="right">79</td>
<td align="right">0.99</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hispanic</td>
<td align="right">231</td>
<td align="right">0.98</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">2805</td>
<td align="right">0.79</td>
<td align="right">5</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">helmet_12m</td>
<td align="right">311</td>
<td align="right">0.98</td>
<td align="right">5</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">text_while_driving_30d</td>
<td align="right">918</td>
<td align="right">0.93</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hours_tv_per_school_day</td>
<td align="right">338</td>
<td align="right">0.98</td>
<td align="right">1</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">school_night_hours_sleep</td>
<td align="right">1248</td>
<td align="right">0.91</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">77</td>
<td align="right">0.99</td>
<td align="right">16.16</td>
<td align="right">1.26</td>
<td align="right">12.00</td>
<td align="right">15.0</td>
<td align="right">16.00</td>
<td align="right">17.00</td>
<td align="right">18.00</td>
<td align="left">▁▂▅▅▇</td>
</tr>
<tr class="even">
<td align="left">height</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">1.69</td>
<td align="right">0.10</td>
<td align="right">1.27</td>
<td align="right">1.6</td>
<td align="right">1.68</td>
<td align="right">1.78</td>
<td align="right">2.11</td>
<td align="left">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">weight</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">67.91</td>
<td align="right">16.90</td>
<td align="right">29.94</td>
<td align="right">56.2</td>
<td align="right">64.41</td>
<td align="right">76.20</td>
<td align="right">180.99</td>
<td align="left">▆▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">physically_active_7d</td>
<td align="right">273</td>
<td align="right">0.98</td>
<td align="right">3.90</td>
<td align="right">2.56</td>
<td align="right">0.00</td>
<td align="right">2.0</td>
<td align="right">4.00</td>
<td align="right">7.00</td>
<td align="right">7.00</td>
<td align="left">▆▂▅▃▇</td>
</tr>
<tr class="odd">
<td align="left">strength_training_7d</td>
<td align="right">1176</td>
<td align="right">0.91</td>
<td align="right">2.95</td>
<td align="right">2.58</td>
<td align="right">0.00</td>
<td align="right">0.0</td>
<td align="right">3.00</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="left">▇▂▅▂▅</td>
</tr>
</tbody>
</table>
<blockquote>
<p>There are significantly high number of missing values under every variable.</p>
</blockquote>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<p>You will first start with analyzing the <code>weight</code> of participants in kilograms. Using visualization and summary statistics, describe the distribution of weights. How many observations are we missing weights from?</p>
<pre class="r"><code>yrbss %&gt;% 
  
#Summarizing summary statistics for &#39;weight&#39;
  summarise(mean_weight = mean(weight, na.rm = TRUE),
            median_weight = median(weight, na.rm = TRUE),
            std_weight = sd(weight, na.rm = TRUE), 
            max_weight = max(weight, na.rm = TRUE), 
            min_weight = min(weight, na.rm = TRUE), 
            count = n(), 
            SE = std_weight/sqrt(count))</code></pre>
<pre><code>## # A tibble: 1 × 7
##   mean_weight median_weight std_weight max_weight min_weight count    SE
##         &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt;
## 1        67.9          64.4       16.9       181.       29.9 13583 0.145</code></pre>
<pre class="r"><code>#Inspecting &#39;weight&#39; 
yrbss %&gt;% 
  select(weight) %&gt;% 
  skimr::skim() </code></pre>
<table>
<caption>(#tab:eda_on_weight)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">Piped data</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">13583</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">weight</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">67.9</td>
<td align="right">16.9</td>
<td align="right">29.9</td>
<td align="right">56.2</td>
<td align="right">64.4</td>
<td align="right">76.2</td>
<td align="right">181</td>
<td align="left">▆▇▂▁▁</td>
</tr>
</tbody>
</table>
<pre class="r"><code>#Plotting Density plot 
ggplot(yrbss, aes(x = weight)) + 
  geom_density() +
  theme_bw() +
  labs(title = &quot;Density of Weight&quot;, x = &quot;Weight&quot;, y = &quot;Count&quot;)</code></pre>
<p><img src="/blogs/youth_files/figure-html/eda_on_weight-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#Plotting Histogram 
ggplot(yrbss, aes(x = weight)) + 
  geom_histogram() +
  theme_bw() +
  labs(title = &quot;Density of Weight&quot;, x = &quot;Weight&quot;, y = &quot;Count&quot;)</code></pre>
<p><img src="/blogs/youth_files/figure-html/eda_on_weight-2.png" width="648" style="display: block; margin: auto;" />
&gt; From the two plots, we can infer that the distribution of ‘weight’ is right skewed. Comparing the mean with the median, we can observe that the mean is higher than the median, which indicates a right-skewed distribution. There are 1004 missing observations in the ‘weight’ variable.</p>
<p>Next, consider the possible relationship between a high schooler’s weight and their physical activity. Plotting the data is a useful first step because it helps us quickly visualize trends, identify strong associations, and develop research questions.</p>
<pre class="r"><code>#Plotting visualizations to glimpse a general relationship between weight and physical activity

#Plot 1
ggplot(yrbss, aes(x = weight , y = physically_active_7d, na.rm = TRUE)) +
  geom_point() + 
  labs(title = &quot;Weight Vs Physical Activity&quot;, x = &quot;Weight&quot;, y = &quot;Physical Activity&quot;)</code></pre>
<p><img src="/blogs/youth_files/figure-html/unnamed-chunk-3-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>yrbss1 &lt;- yrbss %&gt;% 
  filter(physically_active_7d == c(0:7))

#Plot 2
ggplot(yrbss1, aes(x = as.factor(physically_active_7d) , y = weight, na.rm = TRUE)) +
  geom_boxplot() + 
  labs(title = &quot;Weight Vs Physical Activity&quot;, x = &quot;Physical Activity&quot;, y = &quot;Weight&quot;)</code></pre>
<p><img src="/blogs/youth_files/figure-html/unnamed-chunk-3-2.png" width="648" style="display: block; margin: auto;" /></p>
<p>Let’s create a new variable in the dataframe <code>yrbss</code>, called <code>physical_3plus</code> , which will be <code>yes</code> if they are physically active for at least 3 days a week, and <code>no</code> otherwise. You may also want to calculate the number and % of those who are and are not active for more than 3 days. RUse the <code>count()</code> function and see if you get the same results as <code>group_by()... summarise()</code></p>
<pre class="r"><code>#Creating new variable based on condition 
physical_activity &lt;- yrbss %&gt;% 
  
  #Removing NA values
  filter(!is.na(physically_active_7d)) %&gt;% 
  
  #Stating conditions for new variable and adding column
  mutate(physical_3plus = case_when(
          physically_active_7d &gt;= 3 ~&quot;yes&quot;, 
          physically_active_7d &lt; 3 ~&quot;no&quot;),
          physical_3plus = factor(physical_3plus, levels = c(&quot;yes&quot;,&quot;no&quot;)))

#Calculating the number and % of those who are and are not active for more than 3 days using count()
physical_activity %&gt;% 
  count(physical_3plus) %&gt;% 
  mutate(proportions = n/sum(n))</code></pre>
<pre><code>## # A tibble: 2 × 3
##   physical_3plus     n proportions
##   &lt;fct&gt;          &lt;int&gt;       &lt;dbl&gt;
## 1 yes             8906       0.669
## 2 no              4404       0.331</code></pre>
<p>Can you provide a 95% confidence interval for the population proportion of high schools that are <em>NOT</em> active 3 or more days per week?</p>
<pre class="r"><code>#Calculating the number and % of those who are and are not active for more than 3 days using group_by()
physical_activity %&gt;% 
  
  group_by(physical_3plus) %&gt;% 
  
  summarise(n = n()) %&gt;% 
  
  #Calculating 95% CIs
  mutate(proportions = n/sum(n),
         se = sqrt(proportions*(1-proportions)/n),
         lower = proportions - 1.96*se,  
         upper = proportions + 1.96*se)</code></pre>
<pre><code>## # A tibble: 2 × 6
##   physical_3plus     n proportions      se lower upper
##   &lt;fct&gt;          &lt;int&gt;       &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 yes             8906       0.669 0.00499 0.659 0.679
## 2 no              4404       0.331 0.00709 0.317 0.345</code></pre>
<blockquote>
<p>The count() function gives the same output as the group_by()….summarise().</p>
</blockquote>
<p>Make a boxplot of <code>physical_3plus</code> vs. <code>weight</code>. Is there a relationship between these two variables? What did you expect and why?</p>
<pre class="r"><code>physical_activity %&gt;% 
  
  #Plotting boxplot
  ggplot(aes(x=physical_3plus, y=weight)) +
  geom_boxplot() +
  labs(title = &quot; Weight vs Exercises/week&quot;,
       x = &quot;Exercises/week&quot;,
       y = &quot;Weight&quot;)</code></pre>
<p><img src="/blogs/youth_files/figure-html/boxplot-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>favstats(weight ~ physical_3plus, data = physical_activity)</code></pre>
<pre><code>##   physical_3plus  min   Q1 median   Q3 max mean   sd    n missing
## 1            yes 33.1 56.7   65.8 77.1 160 68.4 16.5 8342     564
## 2             no 29.9 54.4   62.6 74.8 181 66.7 17.6 4022     382</code></pre>
<blockquote>
<p>The boxplots do not offer much of a relationship between amount of exercises/week and weight.</p>
</blockquote>
</div>
<div id="confidence-interval" class="section level2">
<h2>Confidence Interval</h2>
<p>Boxplots show how the medians of the two distributions compare, but we can also compare the means of the distributions using either a confidence interval or a hypothesis test. Note that when we calculate the mean, SD, etc. weight in these groups using the mean function, we must ignore any missing values by setting the <code>na.rm = TRUE</code>.</p>
<pre class="r"><code># 95% CIs
physical_activity %&gt;% 
  group_by(physical_3plus) %&gt;% 
  summarise(n = n(),
            mean_weight = mean(weight, na.rm = TRUE))%&gt;% 
  mutate(se = sd(mean_weight, na.rm = TRUE)/sqrt(n),
         lower = mean_weight - 1.96*se,
         upper = mean_weight + 1.96*se)</code></pre>
<pre><code>## # A tibble: 2 × 6
##   physical_3plus     n mean_weight     se lower upper
##   &lt;fct&gt;          &lt;int&gt;       &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 yes             8906        68.4 0.0133  68.4  68.5
## 2 no              4404        66.7 0.0189  66.6  66.7</code></pre>
<pre class="r"><code>#Performing hypothesis test
mosaic::t.test(weight ~ physical_3plus, data = physical_activity)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = 5, df = 7479, p-value = 9e-08
## alternative hypothesis: true difference in means between group yes and group no is not equal to 0
## 95 percent confidence interval:
##  1.12 2.42
## sample estimates:
## mean in group yes  mean in group no 
##              68.4              66.7</code></pre>
<blockquote>
<p>As we can see, the confidence intervals do not overlap. The confidence intervals for difference in weights pertaining to exercise/week does not contain zero. Therefore, there is a statsitical significant difference in the weight of the 2 groups.</p>
</blockquote>
<p>There is an observed difference of about 1.77kg (68.44 - 66.67), and we notice that the two confidence intervals do not overlap. It seems that the difference is at least 95% statistically significant. Let us also conduct a hypothesis test.</p>
</div>
<div id="hypothesis-test-with-formula" class="section level2">
<h2>Hypothesis test with formula</h2>
<p>Write the null and alternative hypotheses for testing whether mean weights are different for those who exercise at least times a week and those who don’t.</p>
<pre class="r"><code>#Given code also performed above for comparison
mosaic::t.test(weight ~ physical_3plus, data = physical_activity)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = 5, df = 7479, p-value = 9e-08
## alternative hypothesis: true difference in means between group yes and group no is not equal to 0
## 95 percent confidence interval:
##  1.12 2.42
## sample estimates:
## mean in group yes  mean in group no 
##              68.4              66.7</code></pre>
</div>
<div id="hypothesis-test-with-infer" class="section level2">
<h2>Hypothesis test with <code>infer</code></h2>
<p>Next, we will introduce a new function, <code>hypothesize</code>, that falls into the infer workflow. You will use this method for conducting hypothesis tests.</p>
<p>But first, we need to initialize the test, which we will save as <code>obs_diff</code>.</p>
<pre class="r"><code>obs_diff &lt;- physical_activity %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))

obs_diff</code></pre>
<pre><code>## Response: weight (numeric)
## Explanatory: physical_3plus (factor)
## # A tibble: 1 × 1
##    stat
##   &lt;dbl&gt;
## 1  1.77</code></pre>
<p>Notice how you can use the functions specify and calculate again like you did for calculating confidence intervals. Here, though, the statistic you are searching for is the difference in means, with the order being yes - no != 0.</p>
<p>After you have initialized the test, you need to simulate the test on the null distribution, which we will save as null.</p>
<pre class="r"><code>null_dist &lt;- physical_activity %&gt;%
  # specify variables
  specify(weight ~ physical_3plus) %&gt;%
  
  # assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  # calculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))

null_dist</code></pre>
<pre><code>## Response: weight (numeric)
## Explanatory: physical_3plus (factor)
## Null Hypothesis: independence
## # A tibble: 1,000 × 2
##    replicate    stat
##        &lt;int&gt;   &lt;dbl&gt;
##  1         1  0.425 
##  2         2  0.543 
##  3         3  0.714 
##  4         4  0.176 
##  5         5  0.578 
##  6         6 -0.212 
##  7         7  0.0470
##  8         8  0.350 
##  9         9  0.286 
## 10        10  0.250 
## # … with 990 more rows</code></pre>
<p>Here, <code>hypothesize</code> is used to set the null hypothesis as a test for independence, i.e., that there is no difference between the two population means. In one sample cases, the null argument can be set to <em>point</em> to test a hypothesis relative to a point estimate.</p>
<p>Also, note that the <code>type</code> argument within generate is set to permute, which is the argument when generating a null distribution for a hypothesis test.</p>
<p>We can visualize this null distribution with the following code:</p>
<pre class="r"><code>ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram() +
  labs(title = &quot;Null distribution of weight ~ exercise/week&quot;)</code></pre>
<p><img src="/blogs/youth_files/figure-html/unnamed-chunk-5-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Now that the test is initialized and the null distribution formed, we can visualise to see how many of these null permutations have a difference of at least <code>obs_stat</code> of 1.77?</p>
<p>We can also calculate the p-value for your hypothesis test using the function <code>infer::get_p_value()</code>.</p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/blogs/youth_files/figure-html/unnamed-chunk-6-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p>This the standard workflow for performing hypothesis tests.</p>
</div>
</div>
